### PR TITLE
🐛 fix issue where data sorter does not pick up changes to the model

### LINKED ISSUE #39: data not refreshed when model changes when using data-sorter
same cause of #17 -- but the fix for that was only applied to `data-filterer`.  that same fix needs to be applied to `data-sorter` as well (and maybe other components)

basically when you have code like this:

```handlebars
      {{#data-sorter data=model as |ds|}}
        {{#data-table data=ds.data as |t|}}
          {{t.sortableColumn propertyName='name' name="Name"}}
        {{/data-table}}
      {{/data-sorter}}
```

if the model changes, the table does not show the new data

the fix is the same as for #17 (fixed by #18)

```diff
-  sortedData:computed('data', 'sortFields.[]', 'sorter', function() {
+  sortedData:computed('data.[]', 'sortFields.[]', 'sorter', function() {
```

### PR DESCRIPTION
**Pull request by ctcpip**
resolves #39

### CODE REVIEW

**Comment by ctcpip** [comment]
@ahmetemrekilinc  🙂

**Comment by ahmetemrekilinc** [comment]
@ctcpip thank you. I've just published 3.0.1

**Comment by ctcpip** [comment]
@ahmetemrekilinc Great, thanks for the fast response!

**Comment by ykaragol** [comment]
thank you @ctcpip

**Pull request merged**
